name: Docker Image
on: 
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:
    paths: 
      - .github/workflows/dockerimage.yml
      - build.sh
      - Dockerfile
      - protoc-wrapper
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  
      with:
        install: true

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: strophy/protoc
        tags: |
          type=raw,value=development,enable=${{ github.ref == 'refs/heads/main' }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=tag
        flavor: |
          latest=auto

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Load dependency versions
      run: cat deps.list >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        build-args: |
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          DART_PROTOBUF_VERSION=${{ env.DART_PROTOBUF_VERSION }}
          DART_VERSION=${{ env.DART_VERSION }}
          GO_VERSION=${{ env.GO_VERSION }}
          GOOGLE_API_VERSION=${{ env.GOOGLE_API_VERSION }}
          GOTEMPLATE_VERSION=${{ env.GOTEMPLATE_VERSION }}
          GRPC_GATEWAY_VERSION=${{ env.GRPC_GATEWAY_VERSION }}
          GRPC_JAVA_VERSION=${{ env.GRPC_JAVA_VERSION }}
          GRPC_RUST_VERSION=${{ env.GRPC_RUST_VERSION }}
          GRPC_SWIFT_VERSION=${{ env.GRPC_SWIFT_VERSION }}
          GRPC_VERSION=${{ env.GRPC_VERSION }}
          GRPC_WEB_VERSION=${{ env.GRPC_WEB_VERSION }}
          JSONSCHEMA_VERSION=${{ env.JSONSCHEMA_VERSION }}
          NODE_VERSION=${{ env.NODE_VERSION }}
          PROTOBUF_C_VERSION=${{ env.PROTOBUF_C_VERSION }}
          PROTOC_GEN_DOC_VERSION=${{ env.PROTOC_GEN_DOC_VERSION }}
          PROTOC_GEN_GO_GRPC_VERSION=${{ env.PROTOC_GEN_GO_GRPC_VERSION }}
          PROTOC_GEN_GO_VERSION=${{ env.PROTOC_GEN_GO_VERSION }}
          PROTOC_GEN_GOGO_VERSION=${{ env.PROTOC_GEN_GOGO_VERSION }}
          PROTOC_GEN_GOVALIDATORS_VERSION=${{ env.PROTOC_GEN_GOVALIDATORS_VERSION }}
          PROTOC_GEN_GQL_VERSION=${{ env.PROTOC_GEN_GQL_VERSION }}
          PROTOC_GEN_LINT_VERSION=${{ env.PROTOC_GEN_LINT_VERSION }}
          PROTOC_GEN_VALIDATE_VERSION=${{ env.PROTOC_GEN_VALIDATE_VERSION }}
          RUST_PROTOBUF_VERSION=${{ env.RUST_PROTOBUF_VERSION }}
          RUST_VERSION=${{ env.RUST_VERSION }}
          SWIFT_VERSION=${{ env.SWIFT_VERSION }}
          TS_PROTOC_GEN_VERSION=${{ env.TS_PROTOC_GEN_VERSION }}
          UPX_VERSION=${{ env.UPX_VERSION }}
